@startuml
!theme plain
hide empty members

package "React Components" {
  object GraphPage {
+ Entry point to the graph view
+ Thought preview overlay
+ Zoom and time slider controls
  }

  object GraphContainer {
+ Holds the PixiJS application object
  }
}


package "State and Parameters" {
  object GraphStore {
+ Zustand state of the graph view
+ Accessed by all files below
  }
  object GraphParameters {
+ constants for FDL and other behavior
+ Accessed by all files below
  }
}

package Simulation {
  object GraphRunner {
+ Main logic loop of the graph simulation
  }

  object ForcesSimulation {
+ FDL implementation
  }
  object ThoughtsProvider {
+ Provides and updates thought arrays
  }
}

package View {
  object GraphGraphics {
+ Pixi.js rendering logic
  }
  object ViewportInitializer {
+ Initializes panning controls
  }
}


"ForcesSimulation" <-[hidden]- "ThoughtsProvider" 
GraphPage -> GraphContainer : "Contains"
GraphContainer --> GraphRunner : "Runs"
GraphRunner ---> GraphGraphics : "Initiaizes and renders once per frame"
ViewportInitializer <- GraphGraphics: "On initialization"
ForcesSimulation <- GraphRunner : "Computes positions once per frame"
"State and Parameters" <--[hidden] "React Components"
@enduml